import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from data_extraction import dataset

'''
Given x in {+-}^N, for some measure p(x), learn a generative model
Configurations generated by z in R^d such that p(x) = Integral p(x|z)p(z)dz
Perform log-likelyhood - by variational autoencoder
'''

class Encoder(nn.Module):
    def __init__(self, latent_dim):
        super().__init__()

        # dimensional reduction
        self.conv = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=4, stride=2, padding=1),  # 200x200 -> 100x100
            nn.ReLU(),
            nn.Conv2d(32, 64, kernel_size=4, stride=2, padding=1), # 100x100 -> 50x50
            nn.ReLU(),
            nn.Conv2d(64, 128, kernel_size=4, stride=2, padding=1),# 50x50 -> 25x25
            nn.ReLU(),
        )

        self.fc_mu = nn.Linear(128*25*25, latent_dim)
        self.fc_log_sigma = nn.Linear(128*25*25, latent_dim) # we want to output log sigma, because sigma has to be positive

    def forward(self, x):
        h = self.conv(x)
        h = h.view(h.size(0), -1) # flatten the shape
        mu = self.fc_mu(h)
        log_sigma = self.fc_log_sigma(h)
        return mu, log_sigma

def reparameterize(mu, log_sigma):
    epsilon = torch.randn_like(mu)
    z = mu + torch.exp(log_sigma) * epsilon
    return z

class Decoder(nn.Module):
    def __init__(self, latent_dim):
        super().__init__()
        
        # First expand z back to a spatial feature map
        self.fc = nn.Linear(latent_dim, 128 * 25 * 25)
        
        # Then upsample back to 200x200, "dconvolve"
        self.deconv = nn.Sequential(
            nn.ConvTranspose2d(128, 64, kernel_size=4, stride=2, padding=1), # 25x25 -> 50x50
            nn.ReLU(),
            nn.ConvTranspose2d(64, 32, kernel_size=4, stride=2, padding=1),  # 50x50 -> 100x100
            nn.ReLU(),
            nn.ConvTranspose2d(32, 1, kernel_size=4, stride=2, padding=1),   # 100x100 -> 200x200
            nn.Tanh(),  # output in [-1, +1], matching spin values
        )
    
    def forward(self, z):
        h = self.fc(z)
        h = h.view(h.size(0), 128, 25, 25)  # unflatten
        x_reconstructed = self.deconv(h)
        return x_reconstructed


class VAE(nn.Module):
    def __init__(self, latent_dim) -> None:
        super().__init__()

        self.encoder = Encoder(latent_dim)
        self.decoder = Decoder(latent_dim)


    def forward(self, x):
        # Encode
        mu, log_sigma = self.encoder(x)

        # Reparameterize
        z = reparameterize(mu, log_sigma)

        # Decode
        x_reconstructed = self.decoder(z)

        return x_reconstructed, mu, log_sigma



def vae_loss(x, x_reconstructed, mu, log_sigma):
    # Reconstruction term — how well did we reconstruct x?
    reconstruction = nn.functional.mse_loss(x_reconstructed, x, reduction='sum') / x.size(0)

    # KL term — closed form for two Gaussians
    kl = -0.5 * torch.sum(1 + 2*log_sigma - mu**2 - torch.exp(2*log_sigma)) / x.size(0)

    return reconstruction + kl

class IsingDataset(Dataset):
    def __init__(self, dataset):
        self.sigma = [d["sigma"] for d in dataset]

        betas = np.array([d["beta"] for d in dataset], dtype=np.float32)
        hs = np.array([d["h"] for d in dataset], dtype=np.float32)

        # normalize conditioning labels so beta and h sit on comparable scales
        self.beta_mean, self.beta_std = betas.mean(), betas.std() or 1.0
        self.h_mean, self.h_std = hs.mean(), hs.std() or 1.0

        self.betas = (betas - self.beta_mean) / self.beta_std
        self.hs = (hs - self.h_mean) / self.h_std

    def __len__(self):
        return len(self.sigma)

    def __getitem__(self, idx):
        x = torch.tensor(self.sigma[idx], dtype=torch.float32).unsqueeze(0)  # (1, 200, 200)
        y = torch.tensor([self.betas[idx], self.hs[idx]], dtype=torch.float32)
        return x, y


def train():

    latent_dim = 64
    epochs = 150
    batch_size = 16

    model = VAE(latent_dim)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

    train_loader = DataLoader(IsingDataset(dataset), batch_size=batch_size, shuffle=True)

    for epoch in range(epochs):
        total_loss = 0.0

        for x, y in train_loader:   # train_loader
            optimizer.zero_grad()   # clear gradients from previous step

            x_reconstructed, mu, log_sigma = model(x)  # forward pass

            loss = vae_loss(x, x_reconstructed, mu, log_sigma)  # compute loss

            loss.backward()         # backpropagation
            optimizer.step()        # updating weights

            total_loss += loss.item()   
        print(f"Epoch {epoch+1}/{epochs} | Loss: {total_loss / len(train_loader):.4f}")
train()
